[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/profile/:slug"
  to = "/profile.html?slug=:slug"
  status = 200

[[redirects]]
  from = "/*"
  to = "/under-construction.html"
  status = 404

[dev]
  publish = "."
  functions = "netlify/functions"
